# Generated by Django 5.0.6 on 2024-06-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('Client', 'Client'), ('Organisateur', 'Organisateur'), ('Admin', 'Admin')], max_length=255)),
                ('addresse', models.CharField(max_length=500)),
                ('profile_img', models.ImageField(blank=True, default='profile_img_default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Admininstrateur',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_app.users')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
            ],
            bases=('users_app.users',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_app.users')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
            ],
            bases=('users_app.users',),
        ),
        migrations.CreateModel(
            name='Organisateur',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_app.users')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('categorie', models.CharField(choices=[('ligue 1', 'ligue 1'), ('ligue 2', 'ligue 2'), ('Coupe du tunisie', 'Coupe du tunisie'), ('Amateur ligue', 'Amateur ligue')], max_length=255)),
            ],
            bases=('users_app.users',),
        ),
    ]
