# Generated by Django 5.0.6 on 2024-06-05 00:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='images')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users_app.organisateur')),
            ],
        ),
    ]
